### ISSUE TITLE
Not enough documentation 

### ISSUE THREAD

**Issue by AlexandreCourjaud** [Matthix7/brave_2020_localisation#2]

**Comment by corentin-j** [comment]
I completely agree with that issue, I can't figure out how to use it.

**Comment by AlexandreCourjaud** [comment]
you can follow this example 
https://github.com/QuentinCar/Brave

**Comment by QuentinCar** [comment]
Couldn't agree more

**Comment by Matthix7** [comment]
Bande de pignoufs (en français dans le texte).

**Comment by Matthix7** [comment]
This package will soon be delivered in its fully operable form. Documentation about usage will be added when everything is considered as ready. This package still needs some reorganisation.
For theoretical understanding of is done inside, check out https://github.com/Matthix7/brave_2020_localisation/blob/master/src/Localisation/test_bench_intervals_ros.py.

**Comment by Matthix7** [comment]
I can see you.
